spring.application.name=reviewservice

server.port=8083


spring.datasource.url=jdbc:postgresql://postgres:5432/reviewservice
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




management.Training.sampling.probability=1.0


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
