spring.application.name=jobservice


server.port=8081
spring.cloud.compatibility-verifier.enabled=false



# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate Dialect for H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show SQL Queries
spring.jpa.show-sql=true

# Automatically create/drop schema on startup
spring.jpa.hibernate.ddl-auto=update

# H2 Console Access (Optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# Enable H2 Console for testing (Optional)
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console



eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/



management.Training.sampling.probability=1.0


spring.config.import=optinal:configserver:http://localhost:8080/



# Resilience4j Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.companyBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.companyBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.companyBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.companyBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.companyBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.companyBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.companyBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.companyBreaker.slidingWindowType=count_based

# Spring Boot Actuator Configuration
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always


